### ISSUE TITLE
BoxConstraints has a negative minimum width.

### ISSUE THREAD

**Issue by FadiSweden** [januwA/flutter_video_box#11]
Hey, 
firstly thank you for a hard work.
I got this issue as it was in the previous v.
I use [one video ctrl](https://github.com/januwA/flutter_video_box/blob/master/example/lib/pages/one_video_ctrl.dart) script:
BoxConstraints has a negative minimum width.
The relevant error-causing widget was: 
  VideoBox [THIS LINE](https://github.com/januwA/flutter_video_box/blob/master/example/lib/pages/one_video_ctrl.dart#L23)

and VideoBox  [This](https://github.com/januwA/flutter_video_box/blob/master/example/lib/pages/one_video_ctrl.dart#L116)
Regards

**Comment by januwA** [comment]
Hi, @FadiSweden  Can you provide your mobile phone simulator version and `flutter doctor -v`?
