### ISSUE TITLE
Displays loading when a connection has a problem

### ISSUE THREAD

**Issue by alakreasi** [januwA/flutter_video_box#17]
How do I add loading when the internet connection is having problems?
Thank you

**Comment by januwA** [comment]
Hi, I released `v0.11.0`, and performed a simple optimization on the disconnection and reconnection of the network. 🌈

see also: 
 - https://pub.dev/packages/video_box#-changelog-tab-

**Comment by alakreasi** [comment]
Thank you very much.
You are the best
