### ISSUE TITLE
Displays loading when the connection goes down

### ISSUE THREAD

**Issue by alakreasi** [januwA/flutter_video_box#20]
Hi,
Loading appears when the connection is lost, but loading does not appear when the connection drops and the video stops.

**Comment by januwA** [comment]
Hi, In `v0.11.4`, when the network is disconnected and the buffer loading state is entered, the play/pause button is hidden

**Comment by alakreasi** [comment]
Thank you for your hard work.
But loading only appears when the connection is lost.
When the connection is slow and the video is buffering loading does not appear

**Comment by januwA** [comment]
update to `v0.15.0`
