### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by fuedgabriel** [januwA/flutter_video_box#21]
C:\SRC\flutter\bin\flutter.bat --no-color build apk
You are building a fat APK that includes binaries for android-arm, android-arm64, android-x64.
If you are deploying the app to the Play Store, it's recommended to use app bundles or split the APK to reduce the APK size.
    To generate an app bundle, run:
        flutter build appbundle --target-platform android-arm,android-arm64,android-x64
        Learn more on: https://developer.android.com/guide/app-bundle
    To split the APKs per ABI, run:
        flutter build apk --target-platform android-arm,android-arm64,android-x64 --split-per-abi
        Learn more on:  https://developer.android.com/studio/build/configure-apk-splits#configure-abi-split
Running Gradle task 'assembleRelease'...                        
Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: Some input files use or override a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Note: C:\SRC\flutter\.pub-cache\hosted\pub.dartlang.org\video_player-0.10.8+1\android\src\main\java\io\flutter\plugins\videoplayer\VideoPlayerPlugin.java uses or overrides a deprecated API.

Note: Recompile with -Xlint:deprecation for details.

Calling mockable JAR artifact transform to create file: C:\Users\House\.gradle\caches\transforms-2\files-2.1\80784612055a36fb80116b31921330f1\android.jar with input C:\Users\House\AppData\Local\Android\sdk\platforms\android-28\android.jar

Removed unused resources: Binary resource data reduced from 44KB to 35KB: Removed 20%
Running Gradle task 'assembleRelease'...                          176.8s (!)
√ Built build\app\outputs\apk\release\app-release.apk (49.0MB).
Process finished with exit code 0

**Comment by januwA** [comment]
You can try to run `flutter build apk --split-per-abi`, which is prompted in [Official Document](https://flutter.dev/docs/deployment/android#build-an-apk).

If the project file generated by your flutter is outdated, you can run `flutter create foo` to generate a new project template, you can see [here](https://github.com/flutter/flutter/wiki/Workarounds-for-common-issues#flutter-project-files)

Hope to solve your problem 😊
