### ISSUE TITLE
How to add a title to the video and update the title?

### ISSUE THREAD

**Issue by fuedgabriel** [januwA/flutter_video_box#22]
AspectRatio(
            aspectRatio: 16 / 9,
            child: VideoBox(
              controller: vc,
              children: <Widget>[
                Align(
                  alignment: Alignment((MediaQuery.of(context).size.height * 0.0004)*-1, (MediaQuery.of(context).size.width * 0.0020)*-1),
                  child: Text(
                    **episodeActualy**,
                    style: TextStyle(
                      fontSize: 16,
                      color: Colors.white
                    ),
                  )
                ),
              ],
            ),
          ),

SetState does not work on VideoBox.
setState(() {
        episodeActualy = ' class 01';
      });

**Comment by januwA** [comment]
May need a little trouble......

https://gist.github.com/januwA/ff23035c74c0d60f0b31c15a76c2867f

**Comment by fuedgabriel** [comment]
thank you very much.
