### ISSUE TITLE
How to return to portraitUp mode screen after fullscreen?

### ISSUE THREAD

**Issue by robertoltrocha** [januwA/flutter_video_box#27]
hi
I need that when I close the screen in fullscreen mode, go back to portraitUp mode. Or leave the return to a configurable pattern.
Could you help?
thanks

**Comment by januwA** [comment]
Thank you for your suggestion, I will try to fix it, but I still have no way to test 👍

**Comment by januwA** [comment]
https://gist.github.com/januwA/2eec33471ceacb1f57de8c364f2ee244  Hope this helps you 😃

**Comment by robertoltrocha** [comment]
Hi,
It is working. 

Thanks for your help
