### ISSUE TITLE
The slide control is very close to the edge of the screen

### ISSUE THREAD

**Issue by robertoltrocha** [januwA/flutter_video_box#30]
Hi

I have an S-10 galaxy and the slide control is very close to the edge of the screen and I have a lot of difficulty using this control with my finger.
I would suggest that this slide be placed higher, so that control would fail.
I tested it with an Iphone 7 plus and the case and had the same problem.
![v2](https://user-images.githubusercontent.com/30963205/84834210-43faf000-b007-11ea-849d-d6321ce5e8d7.jpg)

**Comment by Hamidrezana** [comment]
@robertoltrocha  Did you solve this problem?

**Comment by robertoltrocha** [comment]
yes thanks.

**Comment by Hamidrezana** [comment]
@robertoltrocha So, What was your solution?

**Comment by robertoltrocha** [comment]
Hi,
you can use this parameter **bottomPadding** and setting the padding.
```
 vcs = new VideoController(
        bottomPadding: EdgeInsets.all(25),
        customFullScreen: const MyFullScreen(),       
        controllerLiveDuration: Duration(seconds: 10),
        animetedIconDuration: Duration(milliseconds: 200),
```
