### ISSUE TITLE
The play and pause icons are unchanged when another video is selected in the list

### ISSUE THREAD

**Issue by gamestap99** [januwA/flutter_video_box#31]
Hello, master. First, thank you for watch question. Second, you can fix problem about icon play and video in list. When i play one video in list, after chose video another then video old not update icon pause -> play.  I hope you read issues and fix it!

**Comment by januwA** [comment]
Do you mean that when playing 1.MP4 in the playlist and then playing 2.MP4, will it cause 1.MP4 to automatically pause?@gamestap99

**Comment by januwA** [comment]
```dart
  @override
  void initState() {
    super.initState();
    for (var i = 0; i < 4; i++) {
      VideoController vc = VideoController(source: VideoPlayerController.network(src1));

      vc.addListener((controller) {
        if(vc.value.isPlaying) {
          // Traverse the list and pause all the videos that are playing
          vcs.forEach((it) { 
            if(it != vc && it.value.isPlaying) it.pause();
          });
        }
      });

      vc.initialize();
      vcs.add(vc);
    }
  }
```
You can monitor the status of the video, and then change the status of other videos, for [more codes](https://github.com/januwA/flutter_video_box/blob/master/example/lib/pages/list_video.dart)

**Comment by gamestap99** [comment]
thank you! This is what I want

**Comment by gamestap99** [comment]
thank you your question
