### ISSUE TITLE
BoxConstraints has a negative minimum width.

### ISSUE THREAD

**Issue by gamestap99** [januwA/flutter_video_box#35]
BoxConstraints has a negative minimum width.
![image](https://user-images.githubusercontent.com/43195138/95888499-59143f80-0dab-11eb-94b7-4980bb0a6566.png)

**Comment by januwA** [comment]
Oh my God, I can’t believe this error has happened again. Can you provide the `flutter doctor -v` version, and the video_box version

**Comment by gamestap99** [comment]
> Oh my God, I can’t believe this error has happened again. Can you provide the `flutter doctor -v` version, and the video_box version

hey master, that is 
![image](https://user-images.githubusercontent.com/43195138/95981874-916a5b00-0e49-11eb-8340-bcc495c8c1d7.png)
![image](https://user-images.githubusercontent.com/43195138/95982685-98de3400-0e4a-11eb-8d6f-739c431369bc.png)

**Comment by januwA** [comment]
Can I take a look at your code snippet. @gamestap99

**Comment by gamestap99** [comment]
> Can I take a look at your code snippet. @gamestap99

sure
![image](https://user-images.githubusercontent.com/43195138/95992464-2d02c800-0e58-11eb-961e-bc762497d123.png)
![image](https://user-images.githubusercontent.com/43195138/95992491-32f8a900-0e58-11eb-910d-11e0175ffc68.png)

**Comment by januwA** [comment]
I reproduced the code, but no errors appeared. Please try to run `flutter clean` and delete `pubspec.lock`, then update video_box to `v0.15.1` and run `flutter pub get` @gamestap99

**Comment by gamestap99** [comment]
> I reproduced the code, but no errors appeared. Please try to run `flutter clean` and delete `pubspec.lock`, then update video_box to `v0.15.1` and run `flutter pub get` @gamestap99

i tried it and i no seen error.
