### ISSUE TITLE
how to play video have on original size?

### ISSUE THREAD

**Issue by vitulgoyani** [januwA/flutter_video_box#4]

**Comment by januwA** [comment]
I will fix this error ❤

**Comment by januwA** [comment]
![image](https://user-images.githubusercontent.com/22570563/68497510-ac266e00-028f-11ea-8f5b-8ec188416c89.png)
[See also](https://pub.dev/packages/video_box#-readme-tab-)

**Comment by vitulgoyani** [comment]
thank you very much @januwA 👌

**Comment by januwA** [comment]
Thank you very much for your attention. @vitulgoyani

**Comment by vitulgoyani** [comment]
sorry but video is not play

**Comment by vitulgoyani** [comment]
nice but now fullscreen not come back to portrait how to solve this
