### ISSUE TITLE
When video is over then pause icon should be covert in play icon and no loader should show  

### ISSUE THREAD

**Issue by vitulgoyani** [januwA/flutter_video_box#5]
When video is over then pause icon should be covert in play icon and no loader should show.

**Comment by vitulgoyani** [comment]
please help me thank you
When video is over then pause icon should be covert in play icon and no loader should show.

**Comment by januwA** [comment]
> please help me thank you
> When video is over then pause icon should be covert in play icon and no loader should show.

in `v0.7.2` I fixed this error 😄

**Comment by vitulgoyani** [comment]
thank you @januwA
