### ISSUE TITLE
how to play video from the list onTap?

### ISSUE THREAD

**Issue by FadiSweden** [januwA/flutter_video_box#6]
how can add a video image for each in the list and click to play this video
thanks in advance

**Comment by januwA** [comment]
## I hope this helps you.

https://gist.github.com/januwA/d712e24da1a2180afa2c177c24df8b0c


![image](https://user-images.githubusercontent.com/22570563/69505326-4ced7c80-0f64-11ea-8f24-cb3a47129330.png)

**Comment by FadiSweden** [comment]
hey again, i use androidstudio emulator and got this exception error
The following assertion was thrown building Container(bg: BoxDecoration(color: Color(0xffffffff), borderRadius: BorderRadius.circular(10.0)), constraints: BoxConstraints(w=-24.6, h=2.0; NOT NORMALIZED), dirty):
BoxConstraints has a negative minimum width.

The offending constraints were: BoxConstraints(w=-24.6, h=2.0; NOT NORMALIZED)
The relevant error-causing widget was: 
  VideoBox

**Comment by FadiSweden** [comment]
hey again, i use androidstudio emulator and got this exception error on [one_video_cntl.dart](https://github.com/januwA/flutter_video_box/blob/master/example/lib/one_video_ctrl.dart)

The following assertion was thrown building Container(bg: BoxDecoration(color: Color(0xffffffff), borderRadius: BorderRadius.circular(10.0)), constraints: BoxConstraints(w=-24.6, h=2.0; NOT NORMALIZED), dirty):
BoxConstraints has a negative minimum width.

The offending constraints were: BoxConstraints(w=-24.6, h=2.0; NOT NORMALIZED)
The relevant error-causing widget was: 
  VideoBox

**Comment by januwA** [comment]
Thank you for your feedback, I will troubleshoot this issue.😃

**Comment by myomyintaung1411** [comment]
i have a question about how to do pick a video with image picker and play with video box.. is there any solution sir..

**Comment by januwA** [comment]
@myomyintaung1411  Do you mean playing local videos?

**Comment by januwA** [comment]
@myomyintaung1411  https://gist.github.com/januwA/d894c7f16830539e8296f9751d193d62
