### ISSUE TITLE
video seeker slider and timer don't auto update

### ISSUE THREAD

**Issue by vitulgoyani** [januwA/flutter_video_box#8]
Please solve Thank you again

**Comment by vitulgoyani** [comment]
hello please help me😢

**Comment by januwA** [comment]
Received, it is my error that I will troubleshoot, please wait.

**Comment by januwA** [comment]
The plugin has been updated to 0.8.0, please note the api changes

**Comment by vitulgoyani** [comment]
Thank you again and 🌷

**Comment by vitulgoyani** [comment]
one think you can add when video loading you can add circular loader

**Comment by januwA** [comment]
@vitulgoyani Let the user customize the widget during loading?

**Comment by januwA** [comment]
@vitulgoyani  Hi, `v0.9.0` has been updated and added the` customLoadingWidget` API for customization.

**Comment by januwA** [comment]
This issue will be closed, if you have a issue, please reopen a issue.
