### ISSUE TITLE
Compiler message:

### ISSUE THREAD

**Issue by FadiSweden** [januwA/flutter_video_box#9]
i got this issue
Compiler message:
/C:/Users/Dell/flutter/.pub-cache/hosted/pub.dartlang.org/video_box-0.7.2/lib/video.controller.dart:457:11: Error: Superclass has no method named 'dispose'.
    super.dispose();
          ^^^^^^^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
build failed.

FAILURE: Build failed with an exception.

* Where:
Script 'C:\Users\Dell\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 780

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'C:\Users\Dell\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 20s
Finished with error: Gradle task assembleDebug failed with exit code 1

and everything worked fine after i deleted the following line from [video.controller.dart](https://github.com/januwA/flutter_video_box/blob/master/lib/video.controller.dart#L457)

**Comment by januwA** [comment]
The plugin has been updated to 0.8.0, please note the api changes
